apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-demo.fullname" . }}
  labels:
    {{- include "app-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "app-demo.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
