replicaCount: 1

image:
  repository: ghcr.io/jgoroso/myhomelab
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

