name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/jgoroso/app-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest app-demo
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with Helm
        working-directory: app-demo
        run: |
          helm upgrade --install app-demo ./chart \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=${{ github.sha }} \
            --set image.pullPolicy=Always
