name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/jgoroso/app-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: app-demo/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to k3s with Helm
        run: |
          kubectl create ns app-demo --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install app-demo app-demo/chart \
            --namespace app-demo \
            --set image.repository=${{ env.IMAGE }} \
            --set image.tag=latest
